version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai-csv-classifier
    ports:
      - "8501:8501"
    env_file:
      - .env

networks:
  default:
    name: ai-csv-classifier-network
    driver: bridge
