# Target Python 3.12
target-version = "py312"


# Line length to match black's default
line-length = 88

# Enable auto-fixes
fix = true

# Sort imports
src = ["app", "tests", "alembic"]

[lint]
select = [
    "E",   # pycodestyle errors
    "W",   # pycodestyle warnings
    "F",   # pyflakes
    "I",   # isort
    "B",   # flake8-bugbear
    "C4",  # flake8-comprehensions
    "UP",  # pyupgrade
    "N",   # pep8-naming
    "SIM", # flake8-simplify
    "TID", # flake8-tidy-imports
    "RUF", # ruff-specific rules
    "PT",  # pytest style
    "ARG", # unused arguments
]


ignore = [
    "B008",  # Do not perform function calls in argument defaults
    "B904",  # Allow raising exceptions without from clause
    "E501",  # Line too long (handled by formatter)
]


dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[lint.per-file-ignores]
"tests/*" = ["ARG001"]  

[lint.isort]
known-first-party = ["app"]
section-order = ["future", "standard-library", "third-party", "first-party", "local-folder"]
combine-as-imports = true

[lint.pyupgrade]

keep-runtime-typing = true

[lint.pydocstyle]
convention = "google"

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"